### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by abkrim** [JeffreyCA/dashlane-to-keepass#1]
Hi. I not expert on Python.

Get this error with a Export.xlm of dashlane 

```
Processing xxxx.com
Processing xxxxxxx.com
Processing xxxx.ovh
Traceback (most recent call last):
  File "script.py", line 163, in <module>
    main()
  File "script.py", line 161, in main
    writeEntries(xml_file, entries, group, verbose)
  File "script.py", line 102, in writeEntries
    tree.write(filename, encoding='UTF-8', xml_declaration=True)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

A lot of thanks for you script.

**Comment by JeffreyCA** [comment]
Thanks for reporting this issue, I'll take a look later.

**Comment by JeffreyCA** [comment]
I've fixed many issues with the script, the format changed some time ago. It should be fixed now.

**Comment by abkrim** [comment]
Hi.

I pull locale git and after get this erro.

```
➜  dashlane-to-keepass git:(master) python script.py -v ~/ownCloud/Export.json Export.xml
Traceback (most recent call last):
  File "script.py", line 199, in <module>
    main()
  File "script.py", line 194, in main
    entries, ambiguousEntries = readCsv(csv_file, verbose)
  File "script.py", line 38, in readCsv
    for row in reader:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 25: ordinal not in range(128)
```

**Comment by JeffreyCA** [comment]
Okay I think I fixed it now. The issue is specific to Python 2, where characters like `ñ` are not read correctly.

**Comment by abkrim** [comment]
Hi.

I've change sensible data. Try with python and python 3

```
➜  dashlane-to-keepass git:(master) python3 script.py -v ~/Desktop/Export.json Export.xml
Skipped: ['      "password": "W\\\\\\"\\"gykSh}QJn2\\"', '', 'templatemonster.com', 'Antiguos\\\\Externos', '0\\nhttp://', 'tamainut', 'tKlWWWP8sqYoL', '', 'that1design.com // vBulletin templates', 'Antiguos\\\\Externos', '0\\nhttp://tickets.cpanel.net', 'ceo@islaserver.com', 'IYSQ{|4R:dT', '\\"store --> gNEWArP"', '']
Skipped:  30 Apr 2007 19:01:35 +0200\n                        Received: from [69.57.888.64] (port=25190 helo=rocketmule.net)\n                                by ns31.dnsenred.net with esmtps (TLSv1:AES256-SHA:256)\n                                (Exim 4.63)\n                                (envelope-from <anonymous@rocketmule.net>)\n                                id 1HiZFn-0005M0-Ac\n                                for administracion@fenixer.es; Mon
Skipped:  about section and profile picture for your bot
The following password entries were found to be ambiguous due to double quotation marks (") in its fields.
Please manually add the passwords for these sites:

 30 Apr 2007 19:01:35 +0200\n                        Received: from [69.57.99.64] (port=25190 helo=rocketmule.net)\n                                by ns31.dnsenred.net with esmtps (TLSv1:AES256-SHA:256)\n                                (Exim 4.63)\n                                (envelope-from <anonymous@rocketmule.net>)\n                                id 1HiZFn-0005M0-Ac\n                                for administracion@fenixer.es; Mon
 about section and profile picture for your bot


Successfully converted 0 password entries.
➜  dashlane-to-keepass git:(master) ✗ python script.py -v ~/Desktop/Export.json Export.xml
Traceback (most recent call last):
  File "script.py", line 199, in <module>
    main()
  File "script.py", line 194, in main
    entries, ambiguousEntries = readCsv(csv_file, verbose)
  File "script.py", line 38, in readCsv
    for row in reader:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 25: ordinal not in range(128)
```

**Comment by JeffreyCA** [comment]
I noticed you are using a `.json` file? This script only works with `.csv` files.

**Comment by abkrim** [comment]
Oh my god.

I apologize for inconvenients....

Export on CSV and script work fine now

> Successfully converted 1326 password entries.

Sorry.
